/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2025-2025. All rights reserved.
 * MemFabric_Hybrid is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
*/
#ifndef MF_HYBRID_HYBM_PTRACER_H
#define MF_HYBRID_HYBM_PTRACER_H

#include "ptracer.h"

enum MF_HYBM_MOD {
    TP_HYBM_START = PTRACER_ID(0, 0U),
    TP_HYBM_SDMA_LH_TO_GH,
    TP_HYBM_SDMA_LH_TO_GD,
    TP_HYBM_SDMA_LD_TO_GH,
    TP_HYBM_SDMA_LD_TO_GD,

    TP_HYBM_SDMA_GH_TO_LD,
    TP_HYBM_SDMA_GH_TO_LH,
    TP_HYBM_SDMA_GD_TO_LD,
    TP_HYBM_SDMA_GD_TO_LH,

    TP_HYBM_SDMA_GH_TO_GH,
    TP_HYBM_SDMA_GH_TO_GD,
    TP_HYBM_SDMA_GD_TO_GD,
    TP_HYBM_SDMA_GD_TO_GH,

    TP_HYBM_SDMA_BATCH_GH_TO_LD,
    TP_HYBM_SDMA_BATCH_LD_TO_GH,
    TP_HYBM_SDMA_BATCH_GD_TO_LD,
    TP_HYBM_SDMA_BATCH_LD_TO_GD,
    TP_HYBM_SDMA_BATCH_LH_TO_GH,
    TP_HYBM_SDMA_BATCH_GH_TO_LH,
    TP_HYBM_SDMA_BATCH_GD_TO_LH,
    TP_HYBM_SDMA_BATCH_LH_TO_GD,
    TP_HYBM_SDMA_BATCH_GD_TO_GD,
    TP_HYBM_SDMA_BATCH_GD_TO_GH,
    TP_HYBM_SDMA_BATCH_GH_TO_GD,
    TP_HYBM_SDMA_BATCH_GH_TO_GH,
    TP_HYBM_SDMA_BATCH_G_TO_G,

    TP_HYBM_SDMA_LD_TO_GH_ASYNC,
    TP_HYBM_SDMA_GH_TO_LD_ASYNC,

    TP_HYBM_SDMA_WAIT,
    TP_HYBM_SDMA_PUT_WAIT,

    TP_HYBM_SDMA_SUBMIT_G2G_TASK,
    TP_HYBM_SDMA_G2G_SYNC,

    TP_HYBM_SDMA_G2G_HAL_QUERY_SQ_HEAD,
    TP_HYBM_SDMA_G2G_HAL_QUERY_SQ_STATUS,
    TP_HYBM_SDMA_G2G_HAL_RECEIVE_CQE,

    TP_HYBM_EXTEND_COPY,
    TP_HYBM_EXTEND_BATCH_COPY,
    TP_HYBM_EXTEND_BATCH_COPY_QUANT,

    TP_HYBM_HOST_RDMA_LH_TO_GH,
    TP_HYBM_HOST_RDMA_LH_TO_GD,
    TP_HYBM_HOST_RDMA_LD_TO_GH,
    TP_HYBM_HOST_RDMA_LD_TO_GD,
    TP_HYBM_HOST_RDMA_READ_REMOTE,
    TP_HYBM_HOST_RDMA_READ_REMOTE_ASYNC,
    TP_HYBM_HOST_RDMA_READ_REMOTE_ASYNC_SUBMIT,
    TP_HYBM_HOST_RDMA_READ_REMOTE_ASYNC_WAIT,
    TP_HYBM_HOST_RDMA_HCOM_CH_GET,
    TP_HYBM_HOST_RDMA_BATCH_LH_TO_LH,
    TP_HYBM_HOST_RDMA_BATCH_RH_TO_LH,
    TP_HYBM_HOST_RDMA_BATCH_LOCAL_COPY,

    TP_HYBM_HOST_RDMA_BATCH_GH_TO_LD,
    TP_HYBM_HOST_RDMA_BATCH_GH_TO_LH,
    TP_HYBM_HOST_RDMA_BATCH_GD_TO_LD,
    TP_HYBM_HOST_RDMA_BATCH_GD_TO_LH,

    TP_HYBM_HOST_RDMA_BATCH_GH_TO_GH,
    TP_HYBM_HOST_RDMA_BATCH_GH_TO_GD,
    TP_HYBM_HOST_RDMA_BATCH_GD_TO_GD,
    TP_HYBM_HOST_RDMA_BATCH_GD_TO_GH,

    TP_HYBM_RDMA_LH_TO_GH,
    TP_HYBM_RDMA_LH_TO_GD,
    TP_HYBM_RDMA_LD_TO_GH,
    TP_HYBM_RDMA_LD_TO_GD,

    TP_HYBM_RDMA_GH_TO_LD,
    TP_HYBM_RDMA_GH_TO_LH,
    TP_HYBM_RDMA_GD_TO_LD,
    TP_HYBM_RDMA_GD_TO_LH,

    TP_HYBM_RDMA_GH_TO_GH,
    TP_HYBM_RDMA_GH_TO_GD,
    TP_HYBM_RDMA_GD_TO_GD,
    TP_HYBM_RDMA_GD_TO_GH,

    TP_HYBM_RDMA_BATCH_GH_TO_LD,
    TP_HYBM_RDMA_BATCH_LD_TO_GH,
    TP_HYBM_RDMA_BATCH_GD_TO_LD,
    TP_HYBM_RDMA_BATCH_LD_TO_GD,
    TP_HYBM_RDMA_BATCH_GD_TO_LH,
    TP_HYBM_RDMA_BATCH_LH_TO_GD,
    TP_HYBM_RDMA_BATCH_LH_TO_GH,
    TP_HYBM_RDMA_BATCH_GH_TO_GH,
    TP_HYBM_RDMA_BATCH_GH_TO_GD,
    TP_HYBM_RDMA_BATCH_GH_TO_LH,
    TP_HYBM_RDMA_BATCH_GD_TO_GH,
    TP_HYBM_RDMA_BATCH_GD_TO_GD,
    TP_HYBM_RDMA_BATCH_DEFAULT,
    TP_HYBM_RDMA_BATCH_WAIT_W,
    TP_HYBM_RDMA_BATCH_WAIT_R,
    TP_HYBM_DEV_RDMA_ASYNC_WRITE,
    TP_HYBM_DEV_RDMA_ASYNC_READ,
    TP_HYBM_DEV_SEND_WR,
    TP_HYBM_DEV_SUBMIT_TASK,
    TP_HYBM_RDMA_SYNC_TOTAL,
    TP_HYBM_RDMA_SYNC_NOTIFY_WAIT,
    TP_HYBM_RDMA_BATCH_LOCAL,

    TP_HYBM_ACL_BATCH_LD_TO_LH,
    TP_HYBM_ACL_BATCH_LH_TO_LD,
    TP_HYBM_RDMA_BATCH_REG_COPY,

    INDIRECT_EPOOL_WAIT,
    INDIRECT_SENDER_QUEUE_REQ_SCHE,
    INDIRECT_SENDER_QUEUE_RSP_SCHE,
    INDIRECT_WRITE_OUT_SCHE,

    INDIRECT_SENDER_SEND_CNT,
    INDIRECT_SENDER_RECV_CNT,
    INDIRECT_RECEIVER_SEND_CNT,
    INDIRECT_RECEIVER_RECV_CNT,

    INDIRECT_SENDER_PHASE_0,
    INDIRECT_SENDER_PHASE_0_W,
    INDIRECT_SENDER_PHASE_0_W_D2D,
    INDIRECT_SENDER_PHASE_0_W_D2R,
    INDIRECT_SENDER_PHASE_0_R,
    INDIRECT_SENDER_PHASE_0_R_R2D,
    INDIRECT_SENDER_PHASE_0_R_D2D,
    INDIRECT_SENDER_PHASE_1,
    INDIRECT_SENDER_PHASE_1_R,
    INDIRECT_SENDER_PHASE_1_W,

    INDIRECT_RECEIVER_PHASE_0,
    INDIRECT_RECEIVER_PHASE_0_R,
    INDIRECT_RECEIVER_PHASE_0_R_H2D,
    INDIRECT_RECEIVER_PHASE_0_W,
    INDIRECT_RECEIVER_PHASE_0_SCHE,
    INDIRECT_RECEIVER_PHASE_1,
    INDIRECT_RECEIVER_PHASE_1_R,
    INDIRECT_RECEIVER_PHASE_1_W,
    INDIRECT_RECEIVER_PHASE_1_W_D2H,
    INDIRECT_RECEIVER_PHASE_1_SCHE,

    INDIRECT_RANK_ID_LOCAL_COPY,
    INDIRECT_OUT_BAND_SEND_MSG,
    INDIRECT_OUT_BAND_RECV_MSG,
    INDIRECT_WRITE_GATHER_COPY,
    INDIRECT_WRITE_SINGLE_RDMA,
    INDIRECT_READ_SINGLE_RDMA,
    INDIRECT_READ_SCATTER_COPY,
    INDIRECT_ALL_DONE_SEND_MSG,
    INDIRECT_ALL_DONE_RECV_MSG,
    INDIRECT_ALL_DONE_CLEAR_RES,

    INDIRECT_SEND_READ_RECV_ADDR,
    INDIRECT_SEND_READ_RD2D_D2D,
    INDIRECT_SEND_READ_SEND_DONE,
    INDIRECT_SEND_READ_WAIT_ACK,

    INDIRECT_SEND_WRITE_RECV_ADDR,
    INDIRECT_SEND_WRITE_D2D_D2RD,
    INDIRECT_SEND_WRITE_SEND_DONE,
    INDIRECT_SEND_WRITE_WAIT_ACK,

    INDIRECT_RECV_SLICES,
    INDIRECT_RECV_WRITE_SEND_ADDR,
    INDIRECT_RECV_WRITE_WAIT_DONE,
    INDIRECT_RECV_WRITE_D2H,
    INDIRECT_RECV_WRITE_SEND_ACK,

    INDIRECT_RECV_READ_SEND_ADDR,
    INDIRECT_RECV_READ_WAIT_DONE,
    INDIRECT_RECV_READ_H2D,
    INDIRECT_RECV_READ_SEND_ACK,
};

#endif // MF_HYBRID_HYBM_PTRACER_H